### ISSUE TITLE
Some Mods that install differently do not work

### ISSUE THREAD

**Issue by hovrawl** [Elaviers/GCManager#2]
It appears some mods such as https://thunderstore.io/package/TheRealElysium/SetBuildID/ that install to monomod folder does not copy after install

**Comment by Elaviers** [comment]
This is a known issue.
It's hard to sort this out as there is no standard for defining if your mod is a bepinex plugin or a monomod patch... the manager currently just assumes everything is a bepinex plugin.

The only way to resolve this issue right now would be to hard-code a case for each specific monomod patch, which is far from ideal! :/

**Comment by hovrawl** [comment]
Ah I see, is there an issue for the thunderstore github that we are aware of that they will implement a modapi definition that creators can tag their mods against so mod managers could them implement an install method based on the api. Also might be worth mentioning on the manager page that it only works with bepinex plugin

**Comment by Elaviers** [comment]
I've updated the readme.

**Comment by Elaviers** [comment]
beda4428394fe21a3d698590b8df090067c2ed1b
