### ISSUE TITLE
Crash when installing MOD

### ISSUE THREAD

**Issue by utsubox** [Elaviers/GCManager#4]
I use a translation site. I'm not used to writing reports.

After starting the GC Manager, an attempt to install the MOD will crash. There seems to be a problem during the download. I pasted the picture.
![crash](https://user-images.githubusercontent.com/50204025/57079656-c35a3100-6d2b-11e9-8ecb-389baf264cb9.png)

The OS is Windows 7 64 bit, Japanese language.
Below is the crash report.
  問題イベント名:	CLR20r3
  問題の署名 01:	GCManager.exe
  問題の署名 02:	1.3.4.0
  問題の署名 03:	a5169176
  問題の署名 04:	GCManager
  問題の署名 05:	1.3.4.0
  問題の署名 06:	a5169176
  問題の署名 07:	5d
  問題の署名 08:	24
  問題の署名 09:	System.IO.FileNotFoundException
  OS バージョン:	6.1.7601.2.1.0.768.3
  ロケール ID:	1041
  追加情報 1:	0a9e
  追加情報 2:	0a9e372d3b4ad19135b953a78882e789
  追加情報 3:	0a9e
  追加情報 4:	0a9e372d3b4ad19135b953a78882e789

When I searched for CLR20r3, I found many pages related to .NET Framework. Is there anything I should do?

**Comment by rurre** [comment]
It doesn't seem like the author mentions this anywhere but you might be missing some dependencies.
Installing [.NET Framework 4.7.2](https://dotnet.microsoft.com/download/dotnet-framework/net472) fixed this issue for me.

**Comment by utsubox** [comment]
> It doesn't seem like the author mentions this anywhere but you might be missing some dependencies.
> Installing [.NET Framework 4.7.2](https://dotnet.microsoft.com/download/dotnet-framework/net472) fixed this issue for me.

Great!
You were right. It worked fine.
Thank you.
